[tool.poetry]
name = "predictfc-ml"
version = "0.1.0"
description = "PredictFC ML Pipeline"
authors = ["BradleyJason"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
scikit-learn = "^1.8.0"
xgboost = "^3.2.0"
scipy = "^1.17.1"
numpy = "^2.4.3"
pandas = "<3"
mlflow = "<3"
dagshub = "^0.6.8"
dvc = "^3.66.1"
python-dotenv = "^1.2.2"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
ruff = "^0.15.5"
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
