[tool.poetry]
name = "predictfc-backend"
version = "0.1.0"
description = "PredictFC REST API"
authors = ["BradleyJason"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
fastapi = "^0.135.1"
uvicorn = "^0.41.0"
sqlalchemy = "^2.0.48"
alembic = "^1.18.4"
psycopg2-binary = "^2.9.11"
pydantic = "^2.12.5"
pydantic-settings = "^2.13.1"
python-dotenv = "^1.2.2"
supabase = "^2.28.0"
understatapi = "^0.7.1"
numpy = "^2.4.3"
pandas = "^3.0.1"
scipy = "^1.17.1"
scikit-learn = "^1.8.0"
pyarrow = "^23.0.1"
xgboost = "^3.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
pytest-cov = "^7.0.0"
ruff = "^0.15.5"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
