"""phase4A_migration_api_football_new_tables

Revision ID: 01f2ec402355
Revises: b8b94b21cccc
Create Date: 2026-03-12 14:27:21.593300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f2ec402355'
down_revision: Union[str, Sequence[str], None] = 'b8b94b21cccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_competition_id'), 'seasons', ['competition_id'], unique=False)
    op.create_table('injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('injury_type', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injuries_match_id'), 'injuries', ['match_id'], unique=False)
    op.create_index(op.f('ix_injuries_player_id'), 'injuries', ['player_id'], unique=False)
    op.create_index(op.f('ix_injuries_season_id'), 'injuries', ['season_id'], unique=False)
    op.create_index(op.f('ix_injuries_team_id'), 'injuries', ['team_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('formation', sa.String(length=10), nullable=True),
    sa.Column('coach_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineups_match_id'), 'lineups', ['match_id'], unique=False)
    op.create_index(op.f('ix_lineups_team_id'), 'lineups', ['team_id'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('assist_player_id', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('extra_minute', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('event_detail', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assist_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_events_match_id'), 'match_events', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_events_team_id'), 'match_events', ['team_id'], unique=False)
    op.create_table('match_odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=True),
    sa.Column('bookmaker_name', sa.String(length=50), nullable=True),
    sa.Column('home_win', sa.Float(), nullable=True),
    sa.Column('draw', sa.Float(), nullable=True),
    sa.Column('away_win', sa.Float(), nullable=True),
    sa.Column('over_25', sa.Float(), nullable=True),
    sa.Column('under_25', sa.Float(), nullable=True),
    sa.Column('btts_yes', sa.Float(), nullable=True),
    sa.Column('btts_no', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_odds_match_id'), 'match_odds', ['match_id'], unique=False)
    op.create_table('lineup_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('api_football_player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=5), nullable=True),
    sa.Column('grid', sa.String(length=10), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['lineups.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineup_players_lineup_id'), 'lineup_players', ['lineup_id'], unique=False)
    op.add_column('competitions', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.add_column('competitions', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('competitions', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('competitions', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_competitions_api_football_id'), 'competitions', ['api_football_id'], unique=True)
    op.drop_column('competitions', 'season')
    op.add_column('matches', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('round', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('venue', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('referee', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_matches_api_football_id'), 'matches', ['api_football_id'], unique=True)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_foreign_key(None, 'matches', 'seasons', ['season_id'], ['id'])
    op.add_column('teams', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('teams', sa.Column('venue_name', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('venue_capacity', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teams_api_football_id'), 'teams', ['api_football_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_api_football_id'), table_name='teams')
    op.drop_column('teams', 'venue_capacity')
    op.drop_column('teams', 'venue_name')
    op.drop_column('teams', 'country')
    op.drop_column('teams', 'api_football_id')
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_api_football_id'), table_name='matches')
    op.drop_column('matches', 'referee')
    op.drop_column('matches', 'venue')
    op.drop_column('matches', 'round')
    op.drop_column('matches', 'season_id')
    op.drop_column('matches', 'api_football_id')
    op.add_column('competitions', sa.Column('season', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_competitions_api_football_id'), table_name='competitions')
    op.drop_column('competitions', 'is_active')
    op.drop_column('competitions', 'logo_url')
    op.drop_column('competitions', 'type')
    op.drop_column('competitions', 'api_football_id')
    op.drop_index(op.f('ix_lineup_players_lineup_id'), table_name='lineup_players')
    op.drop_table('lineup_players')
    op.drop_index(op.f('ix_match_odds_match_id'), table_name='match_odds')
    op.drop_table('match_odds')
    op.drop_index(op.f('ix_match_events_team_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_match_id'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index(op.f('ix_lineups_team_id'), table_name='lineups')
    op.drop_index(op.f('ix_lineups_match_id'), table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_injuries_team_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_season_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_player_id'), table_name='injuries')
    op.drop_index(op.f('ix_injuries_match_id'), table_name='injuries')
    op.drop_table('injuries')
    op.drop_index(op.f('ix_seasons_competition_id'), table_name='seasons')
    op.drop_table('seasons')
    # ### end Alembic commands ###
