"""add crest_url to teams and competitions

Revision ID: 929c0023d19a
Revises: f6fc3a7b81f6
Create Date: 2026-03-11 09:55:39.537391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929c0023d19a'
down_revision: Union[str, Sequence[str], None] = 'f6fc3a7b81f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('crest_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('idx_matches_competition'), table_name='matches')
    op.drop_index(op.f('idx_matches_date'), table_name='matches')
    op.drop_index(op.f('idx_player_stats_match'), table_name='player_stats')
    op.drop_index(op.f('idx_player_stats_player'), table_name='player_stats')
    op.alter_column('predictions', 'predicted_home_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('predictions', 'predicted_away_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('idx_predictions_match'), table_name='predictions')
    op.add_column('teams', sa.Column('crest_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'crest_url')
    op.create_index(op.f('idx_predictions_match'), 'predictions', ['match_id'], unique=False)
    op.alter_column('predictions', 'predicted_away_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('predictions', 'predicted_home_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_index(op.f('idx_player_stats_player'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('idx_player_stats_match'), 'player_stats', ['match_id'], unique=False)
    op.create_index(op.f('idx_matches_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('idx_matches_competition'), 'matches', ['competition_id'], unique=False)
    op.drop_column('competitions', 'crest_url')
    # ### end Alembic commands ###
