"""add_match_stats_table

Revision ID: b8b94b21cccc
Revises: 929c0023d19a
Create Date: 2026-03-11 19:13:28.853446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b94b21cccc'
down_revision: Union[str, Sequence[str], None] = '929c0023d19a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('shots_total', sa.Integer(), nullable=True),
    sa.Column('shots_on_goal', sa.Integer(), nullable=True),
    sa.Column('shots_off_goal', sa.Integer(), nullable=True),
    sa.Column('shots_blocked', sa.Integer(), nullable=True),
    sa.Column('ball_possession', sa.Float(), nullable=True),
    sa.Column('passes_total', sa.Integer(), nullable=True),
    sa.Column('passes_accurate', sa.Integer(), nullable=True),
    sa.Column('passes_pct', sa.Float(), nullable=True),
    sa.Column('corner_kicks', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('offsides', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=True),
    sa.Column('red_cards', sa.Integer(), nullable=True),
    sa.Column('goalkeeper_saves', sa.Integer(), nullable=True),
    sa.Column('expected_goals', sa.Float(), nullable=True),
    sa.Column('api_football_fixture_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_stats_api_football_fixture_id'), 'match_stats', ['api_football_fixture_id'], unique=False)
    op.create_index(op.f('ix_match_stats_match_id'), 'match_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_stats_team_id'), 'match_stats', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_stats_team_id'), table_name='match_stats')
    op.drop_index(op.f('ix_match_stats_match_id'), table_name='match_stats')
    op.drop_index(op.f('ix_match_stats_api_football_fixture_id'), table_name='match_stats')
    op.drop_table('match_stats')
    # ### end Alembic commands ###
